plugins:
  - serverless-offline
  - serverless-plugin-typescript-express

service:
  name: studio-booking-api

custom:
  tableName: demo-users
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  api:
    handler: src/server.handler
    events:
      - http: 'ANY {proxy+}'

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
